repos:
  - repo: local
    hooks:
        - id: pytest
          name: pytest
          language: system
          entry: sh ./services/report.sh
#          entry: python3 -m pytest ./services/tests/auth.py
          pass_filenames: false
          always_run: true
#          files: ^services/.*\.*$
