repos:
  - repo: local
    hooks:
    -   id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        # entry: python -m pytest -v ./services/tests/auth.py
        # entry: .github/hooks/run-tests-and-coverage.sh
        entry: cd services && coverage run -m pytest -s && coverage report && coverage html
        language: system
        pass_filenames: false
        always_run: true

