repos:
  - repo: local
    hooks:
    -   id: pytest-check
        stages: [push]
        types: [python]
        name: pytest-check
        entry: sh .github/hooks/run-tests-and-coverage.sh
        # entry: sh ./services/report.sh
        # entry: cd services && coverage run -m pytest -s && coverage report && coverage html
        language: system
        pass_filenames: false
        always_run: true

        


