

CREATE TABLE IF NOT EXISTS project.embodiments_figures_section_history
(
    section_history_id serial,
    section_id bigint,
    project_id bigint,
    section_type character varying(50) COLLATE pg_catalog."default",
    text text COLLATE pg_catalog."default",
    prompt text COLLATE pg_catalog."default",
    messages jsonb,
    action_type character varying(50) COLLATE pg_catalog."default",
    is_deleted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    modified_at timestamp with time zone DEFAULT now(),
    version bigint DEFAULT 1,
    is_error character varying COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    message_long text COLLATE pg_catalog."default",
    is_selected boolean DEFAULT false,
    prev_section_history_id bigint,
    claim_section_history_id bigint,
    project_history_id bigint,
    prompt_step1 jsonb,
    response_step1 text COLLATE pg_catalog."default",
    prompt_step2 jsonb,
    response_step2 text COLLATE pg_catalog."default",
    prompt_step3 jsonb,
    step_completed bigint,
    is_redraft boolean DEFAULT false,
    diagram_available boolean DEFAULT false,
    completion_tokens bigint,
    prompt_tokens bigint,
    total_tokens bigint,
    list_of_figures text,
    detailed_description_figures text,
    CONSTRAINT embodiments_figures_section_history_pkey PRIMARY KEY (section_history_id)
);